services:

  # MariaDB
  mysql:
    image: mariadb:10.5
    volumes:
      - ./db_data:/var/mysql
      - ./db-init:/docker-entrypoint-initdb.d
      - ./ca.pem:/etc/mysql/ssl/ca.pem
      - ./server-cert.pem:/etc/mysql/ssl/server-cert.pem
      - ./server-key.pem:/etc/mysql/ssl/server-key.pem
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_SSL_CA: /etc/mysql/ssl/ca.pem
      MYSQL_SSL_CERT: /etc/mysql/ssl/server-cert.pem
      MYSQL_SSL_KEY: /etc/mysql/ssl/server-key.pem
    ports:
      - "3306:3306"
    networks:
      - mynet
    secrets:
      - mysql_root_password
      - mysql_user_password

  # Redis
  myredis:
    image: redis:latest
    networks:
      - mynet
    deploy:
      replicas: 1

  # PHP-FPM
  myphp:
    build:
      context: ./src/php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - myredis
    networks:
      - mynet
    deploy:
      replicas: 1

  # Nginx
  mynginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - myphp
    networks:
      - mynet
    deploy:
      replicas: 1

  # phpMyAdmin
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8082:80"
    volumes:
      - ./src/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

secrets:
  mysql_root_password:
    file: src/secrets/mysql_root_password.txt
  mysql_user_password:
    file: src/secrets/mysql_user_password.txt

volumes:
  db_data: 